package Crypt::Passphrase::SaltedHash;

use v5.6;

use strict;
use warnings;

use parent 'Crypt::Passphrase::Validator';

use Digest 1.19  ();
use MIME::Base64 ();

our $VERSION = '0.02';

# ABSTRACT: Validate against Crypt::SaltedHash hashes with Crypt::Passphrase

=begin :prelude

=for stopwords validator

=end :prelude

=head1 SYNOPSIS

    my $authenticator = Crypt::Passphrase->new(
        encoder    => 'Argon2',
        validators => [ 'SaltedHash' ],
    );

    ...

    if (!$authenticator->verify_password($password, $hash)) {
        die "Invalid password";
    }
    elsif ($authenticator->needs_rehash($hash)) {
        my $new_hash = $authenticator->hash_password($password);
        ...
    }

=head1 DESCRIPTION

This module implements a validator against hashes generated by L<Crypt::SaltedHash>.

=cut

my  %DIGESTS = (
    GOST    => [ 256, "GOST" ],
    HMACMD5 => [ 128, "HMAC-MD5" ],     # Note: Digest::HMAC does not work with Crypt::SaltedHash
    HMACSHA => [ 160, "HMAC-SHA-1" ],
    MD2     => [128],
    MD4     => [128],
    MD5     => [128],
    MD6     => [256],
    SHA     => [ 160, "SHA-1" ],
    SHA224  => [ 224, "SHA-224" ],
    SHA256  => [ 256, "SHA-256" ],
    SHA384  => [ 384, "SHA-384" ],
    SHA512  => [ 512, "SHA-512" ],
);

=for Pod::Coverage new

=for Pod::Coverage accepts_hash

=for Pod::Coverage verify_password

=cut

sub new {
    my $class = shift;
    return bless {}, $class;
}

sub accepts_hash {
    my ( $self,     $hash ) = @_;
    my ( $has_salt, $alg )  = $hash =~ /^\{(S)?(\w+)\}/ or return;
    return exists $DIGESTS{ uc $alg };
}

sub verify_password {
    my ( $self, $password, $hash ) = @_;

    my ( $has_salt, $alg ) = $hash =~ /^\{(S)?(\w+)\}/ or return;
    my $meta = $DIGESTS{ uc $alg } or return;

    my $name   = $meta->[1] || $alg;
    my $bytes  = $meta->[0] / 8;
    my $digest = Digest->new($name);
    my $bin    = MIME::Base64::decode_base64( substr( $hash, length($alg) + 2 + ( $has_salt ? 1 : 0 ) ) );
    my $salt   = $has_salt ? substr( $bin, $bytes ) : "";
    my $maybe  = $digest->add( $password . $salt )->digest;

    return $self->secure_compare( $maybe, substr( $bin, 0, $bytes ) );
}

=head1 SEE ALSO

L<Crypt::Passphrase>

L<Crypt::SaltedHash>

=cut

1;
